package com.app.vector.vectores.entity;

import com.app.vector.vectores.view.Cantidad_Decimales;
import com.app.vector.vectores.view.Escala;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CONFIGURATION".
 */
@Entity
public class Configuration {

    @Id
    private Long id;
    private Integer cantDecimal;
    private Integer tipoView;
    private Integer escala;
    private Integer tipoCoordenada;
    private Boolean showHelp;

    public Configuration() {
        this.cantDecimal = 2;
        this.escala = 1;
        this.tipoCoordenada = 0;
        this.tipoView = 0;
        this.showHelp = true;
    }

    public Configuration(Long id) {
        this.id = id;
    }

    @Generated(hash = 1098159833)
    public Configuration(Long id, Integer cantDecimal, Integer tipoView, Integer escala, Integer tipoCoordenada, Boolean showHelp) {
        this.id = id;
        this.cantDecimal = cantDecimal;
        this.tipoView = tipoView;
        this.escala = escala;
        this.tipoCoordenada = tipoCoordenada;
        this.showHelp = showHelp;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getCantDecimal() {
        return cantDecimal;
    }

    public void setCantDecimal(Integer cantDecimal) {
        this.cantDecimal = cantDecimal;
    }

    public void setCantDecimal(Cantidad_Decimales cantDecimal) {
        this.cantDecimal = getCantDecimal(cantDecimal);
    }

    public Integer getTipoView() {
        return tipoView;
    }

    public void setTipoView(Integer tipoView) {
        this.tipoView = tipoView;
    }

    public Integer getEscala() {
        return escala;
    }

    public void setEscala(Integer escala) {
        this.escala = escala;
    }

    public void setEscala(Escala escala) {
        this.escala = getEscala(escala);
    }

    public Integer getTipoCoordenada() {
        return tipoCoordenada;
    }

    public void setTipoCoordenada(Integer tipoCoordenada) {
        this.tipoCoordenada = tipoCoordenada;
    }

    public Boolean getShowHelp() {
        return showHelp;
    }

    public void setShowHelp(Boolean showHelp) {
        this.showHelp = showHelp;
    }

    private int getEscala(Escala escala){
        int newEscala;
        switch (escala){
            case _1N:
                newEscala = 1;
                break;
            case _5N:
                newEscala = 2;
                break;
            case _10N:
                newEscala = 3;
                break;
            case _50N:
                newEscala = 4;
                break;
            case _100N:
                newEscala = 5;
                break;
            case _1000N:
                newEscala = 6;
                break;
            case _10000N:
                newEscala = 7;
                break;
            case _05N:
                newEscala = 0;
                break;
            default:
                newEscala = -1;
                break;
        }
        return newEscala;
    }

    private int getCantDecimal(Cantidad_Decimales cantDecimal){

        switch (cantDecimal){
            case cero:
                return 0;
            case uno:
                return 1;
            case dos:
                return 2;
            case tres:
                return 3;
            case cuatro:
                return 4;
            default:
                return -1;
        }
    }
}
